name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test_humble:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    env:
      ROS_DISTRO: humble
    steps:
    - uses: actions/checkout@v4
    - name: Create dependency repos file
      shell: bash
      run: |
        cat << 'EOF' > /tmp/deps.repos
        {"repositories":
          {"rmw_implementation":
            {"type": "git",
             "url": "https://github.com/BonsaiRobotics/rmw_implementation",
             "version": "humble-bonsai"
            }
          }
        }
        EOF
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
        vcs-repo-file-url: /tmp/deps.repos
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            }
          }
    - uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
  build_and_test_jazzy:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    env:
      ROS_DISTRO: jazzy
    steps:
    - uses: actions/checkout@v4
    - name: Create dependency repos file
      shell: bash
      run: |
        cat << 'EOF' > /tmp/deps.repos
        {"repositories":
          {"rmw_implementation":
            {"type": "git",
             "url": "https://github.com/BonsaiRobotics/rmw_implementation",
             "version": "jazzy-bonsai"
            }
          }
        }
        EOF
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: jazzy
        vcs-repo-file-url: /tmp/deps.repos
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            }
          }
    - uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
