name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test_humble:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            }
          }
    - uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
  build_and_test_jazzy:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: jazzy
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            }
          }
    - uses: actions/upload-artifact@v4
      with:
        name: colcon-logs
        path: ros_ws/log
